CREATE TABLE `communication_transactions` (
  `id` char(36) NOT NULL,
  `tenant_id` char(36) NOT NULL,
  `communication_reference` varchar(40) NOT NULL,
  `correlation_id` varchar(64) NOT NULL,
  `idempotency_key` varchar(200) NOT NULL,
  `user_id` char(36) NULL,
  `actor_user_id` char(36) NULL,
  `channel` varchar(20) NOT NULL DEFAULT 'whatsapp',
  `provider` varchar(20) NOT NULL DEFAULT 'stub',
  `template_key` varchar(80) NOT NULL,
  `template_version` varchar(20) NOT NULL,
  `language` varchar(8) NOT NULL DEFAULT 'en',
  `recipient_e164` varchar(20) NOT NULL,
  `recipient_last4` varchar(4) NOT NULL,
  `status` varchar(32) NOT NULL,
  `provider_message_id` varchar(128) NULL,
  `business_entity_type` varchar(40) NOT NULL,
  `business_entity_id` varchar(64) NOT NULL,
  `business_event_type` varchar(80) NOT NULL,
  `preference_mode` varchar(20) NOT NULL,
  `requested_at` datetime(3) NOT NULL,
  `sent_at` datetime(3) NULL,
  `delivered_at` datetime(3) NULL,
  `read_at` datetime(3) NULL,
  `failed_at` datetime(3) NULL,
  `next_attempt_at` datetime(3) NULL,
  `retry_count` int NOT NULL DEFAULT 0,
  `error_category` varchar(40) NULL,
  `error_code` varchar(40) NULL,
  `error_message` varchar(300) NULL,
  `content_sha256` varchar(64) NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `created_by` char(36) NULL,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `updated_by` char(36) NULL,
  `is_deleted` boolean NOT NULL DEFAULT false,
  PRIMARY KEY (`id`),
  UNIQUE KEY `comm_tx_reference_uidx` (`communication_reference`),
  UNIQUE KEY `comm_tx_tenant_idem_uidx` (`tenant_id`, `idempotency_key`),
  KEY `comm_tx_tenant_created_idx` (`tenant_id`, `created_at`),
  KEY `comm_tx_tenant_status_idx` (`tenant_id`, `status`),
  KEY `comm_tx_provider_msg_idx` (`provider_message_id`),
  KEY `comm_tx_correlation_idx` (`correlation_id`),
  KEY `comm_tx_business_idx` (`tenant_id`, `business_entity_type`, `business_entity_id`),
  KEY `comm_tx_due_idx` (`status`, `next_attempt_at`)
);
--> statement-breakpoint
CREATE TABLE `communication_attempts` (
  `id` char(36) NOT NULL,
  `tenant_id` char(36) NOT NULL,
  `communication_transaction_id` char(36) NOT NULL,
  `attempt_number` int NOT NULL,
  `provider` varchar(20) NOT NULL,
  `provider_message_id` varchar(128) NULL,
  `started_at` datetime(3) NOT NULL,
  `completed_at` datetime(3) NULL,
  `duration_ms` int NULL,
  `http_status` int NULL,
  `status` varchar(32) NOT NULL,
  `error_category` varchar(40) NULL,
  `error_code` varchar(40) NULL,
  `error_message` varchar(300) NULL,
  `request_sha256` varchar(64) NULL,
  `response_sha256` varchar(64) NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `created_by` char(36) NULL,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `updated_by` char(36) NULL,
  `is_deleted` boolean NOT NULL DEFAULT false,
  PRIMARY KEY (`id`),
  KEY `comm_attempt_tx_idx` (`communication_transaction_id`),
  KEY `comm_attempt_tenant_idx` (`tenant_id`)
);
--> statement-breakpoint
CREATE TABLE `communication_provider_events` (
  `id` char(36) NOT NULL,
  `tenant_id` char(36) NULL,
  `provider` varchar(20) NOT NULL,
  `provider_message_id` varchar(128) NOT NULL,
  `event_type` varchar(40) NOT NULL,
  `status` varchar(32) NOT NULL,
  `event_timestamp` varchar(40) NOT NULL DEFAULT '',
  `communication_transaction_id` char(36) NULL,
  `received_at` datetime(3) NOT NULL,
  `processed_at` datetime(3) NULL,
  `signature_valid` boolean NOT NULL DEFAULT false,
  `payload_sha256` varchar(64) NOT NULL,
  `processing_status` varchar(32) NOT NULL,
  `error_code` varchar(40) NULL,
  `error_message` varchar(300) NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `created_by` char(36) NULL,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `updated_by` char(36) NULL,
  `is_deleted` boolean NOT NULL DEFAULT false,
  PRIMARY KEY (`id`),
  UNIQUE KEY `comm_event_dedup_uidx` (`provider`, `provider_message_id`, `status`, `event_timestamp`),
  KEY `comm_event_tx_idx` (`communication_transaction_id`),
  KEY `comm_event_msg_idx` (`provider_message_id`)
);
--> statement-breakpoint
CREATE TABLE `platform_integration_config` (
  `id` char(36) NOT NULL,
  `whatsapp_provider` varchar(20) NOT NULL DEFAULT 'stub',
  `twilio_account_sid` varchar(40) NULL,
  `twilio_api_key_sid` varchar(40) NULL,
  `twilio_api_key_secret_enc` text NULL,
  `twilio_auth_token_enc` text NULL,
  `twilio_whatsapp_from` varchar(32) NULL,
  `twilio_content_sids_json` text NULL,
  `gupshup_source` varchar(20) NULL,
  `gupshup_app_name` varchar(80) NULL,
  `gupshup_api_key_enc` text NULL,
  `gupshup_template_ids_json` text NULL,
  `meta_phone_number_id` varchar(40) NULL,
  `meta_verify_token_enc` text NULL,
  `meta_token_enc` text NULL,
  `meta_app_secret_enc` text NULL,
  `meta_template_names_json` text NULL,
  `daily_send_cap` int NOT NULL DEFAULT 200,
  `status_callback_base_url` varchar(300) NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `created_by` char(36) NULL,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `updated_by` char(36) NULL,
  `is_deleted` boolean NOT NULL DEFAULT false,
  PRIMARY KEY (`id`)
);
